name: tuto_004_dart_only_bloc
description: A simple tutorial for using bloc in a dart application

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  bloc: ^6.1.1

dev_dependencies:
  pedantic: ^1.9.0
