name: tuto_flutter_bloc
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # A mixture between dependency injection and state management, built with widgets for widgets.
  provider: ^4.0.4

  # Helps to implement equality without needing to explicitly override == and hashCode.
  equatable: ^1.1.1

  # A composable, multi-platform, Future-based API for HTTP requests.
  http: ^0.12.0+4

  # Functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^3.0.1
  
  # Widgets that make it easy to integrate blocs and cubits into Flutter. Built to work with package:bloc.
  flutter_bloc: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Tools to write binaries that run builders.
  build_runner: ^1.8.0

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true
