name: tuto_null_safety
description: A simple command-line application demonstrating use of null safety.
version: 1.0.0

environment:
  #sdk: '>=2.10.0 <3.0.0'
  sdk: '>=2.12.0-29 <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety  

dev_dependencies:
  pedantic: ^1.9.0
  
